### ISSUE TITLE
Vault not opening in Editor

### ISSUE THREAD

**Issue by arpangreat** [justnat3/the-vault#1]
I have set 
`export VAULT_EDITOR=/usr/bin/nvim`

but it is not working when calling only `vault` as a command ...

**Comment by justnat3** [comment]
You will also need to include the path to your vault with the following.
```bash
export VAULT_PATH=/path/to/your/vault
```

after both env-vars are set it should run by calling 

```bash
# the title of the note works with spaces.
vault the name of your note
```

let me know what you find 😄 🚀

**Comment by arpangreat** [comment]
I have done it too 
![screenshot-2021-04-06-00:04:37](https://user-images.githubusercontent.com/46556080/113611182-cb375400-966b-11eb-8cb0-fb67c98d3228.png)

**Comment by arpangreat** [comment]
So vault path is where we store our notes right ?

**Comment by justnat3** [comment]
Yes. VAULT_PATH is where the file will be created.

So when you run vault like we discussed above, what does it throw back at you?

**Comment by justnat3** [comment]
What distro are you running? @arpangreat

**Comment by arpangreat** [comment]
Actually it's working now after a system update ... 

Thanks for your help :heart:

closing this issue ...
