### ISSUE TITLE
No way to supply arguments for the editor

### ISSUE THREAD

**Issue by nyxkrage** [justnat3/the-vault#16]
This disallows the use of example 
```
emacs -nw
nvim --noplugin
nvim --clean
```

**Comment by justnat3** [comment]
Since I do not expect a lot of users to use arguments. A simple option would be to add a flag called `--args` or `-a`

As of right now that would be the plan. 

This will be included when the notebones branch gets its new flag/argument system as the old one was quickly becoming far too long.

**Comment by nyxkrage** [comment]
The workaround i came up with was basically
```
let bones_editor: String = env::var("VAULT_EDITOR").expect("Vault Editor not Found");
let (bones_editor, editor_args): (&str, Vec<&str>) = match bones_editor.split_once(' ') {
    Some((editor, args)) => (editor, args.split(' ').collect()),
    None => (&bones_editor, vec![]),
};
````

**Comment by justnat3** [comment]
I see. From what it looks like the runtime arguments for the editor will just be included in bones_editor value?

**Comment by nyxkrage** [comment]
so you would set the EDITOR/VAULT_EDITOR variable to `emacs -nw` and then it would pass editor_args to the spawn command builder with the `.args` though it doesn't work if the actual binary filename or path has spaces in it.

**Comment by nyxkrage** [comment]
though if you decide to use a config file you could go the route of setting up editor presets, like so in the config file
```toml
default="nvim"

[editor.nvim]
command="nvim"
args=""

[editor.emacsterm]
command="emacs"
args="-nw"
```
or something like so, and then have a cli argument for overriding the editor

**Comment by justnat3** [comment]
Right, I feel that far more common on a Windows system. (Spaces in paths or binary names). However, in most cases people will just stick with launching a windows binaries with no arguments.
